# Generated by Django 5.2.3 on 2025-07-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='device',
            name='manufacture_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='assigned_user',
            field=models.CharField(blank=True, default='Unassigned', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('printer', 'Printer'), ('monitor', 'Monitor'), ('cpu', 'CPU'), ('ups', 'UPS'), ('laptop', 'Laptop')], default='printer', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='room_number',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
        ),
    ]
