# Generated by Django 5.2.3 on 2025-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_remove_device_barcode_remove_device_manufacture_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.AddField(
            model_name='device',
            name='assigned',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='device',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='block',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.CharField(choices=[('dell', 'Dell'), ('hp', 'HP'), ('lenovo', 'Lenovo')], default='dell', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='date_acquired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='engraved',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='device',
            name='engravement_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('functional', 'Functional'), ('non_functional', 'Non Functional')], default='functional', max_length=15),
        ),
        migrations.AddField(
            model_name='device',
            name='tag_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('printer', 'Printer'), ('monitor', 'Monitor'), ('cpu', 'CPU'), ('ups', 'UPS'), ('laptop', 'Laptop')], max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
